<a href="https://colab.research.google.com/github/ampham03/grad-assessment/blob/main/grad_assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.7 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [2]:
import torch
from transformers import MarianMTModel, MarianTokenizer
from datasets import load_dataset

In [3]:
model_name = "Helsinki-NLP/opus-mt-en-de"  # English to German
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name)

# load WMT dataset for de-en
de_en_dev = load_dataset("wmt19", "de-en", split='validation')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.27M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


README.md:   0%|          | 0.00/11.3k [00:00<?, ?B/s]

train-00000-of-00016.parquet:   0%|          | 0.00/384M [00:00<?, ?B/s]

train-00001-of-00016.parquet:   0%|          | 0.00/130M [00:00<?, ?B/s]

train-00002-of-00016.parquet:   0%|          | 0.00/102M [00:00<?, ?B/s]

train-00003-of-00016.parquet:   0%|          | 0.00/176M [00:00<?, ?B/s]

train-00004-of-00016.parquet:   0%|          | 0.00/282M [00:00<?, ?B/s]

train-00005-of-00016.parquet:   0%|          | 0.00/183M [00:00<?, ?B/s]

train-00006-of-00016.parquet:   0%|          | 0.00/251M [00:00<?, ?B/s]

train-00007-of-00016.parquet:   0%|          | 0.00/336M [00:00<?, ?B/s]

train-00008-of-00016.parquet:   0%|          | 0.00/232M [00:00<?, ?B/s]

train-00009-of-00016.parquet:   0%|          | 0.00/224M [00:00<?, ?B/s]

train-00010-of-00016.parquet:   0%|          | 0.00/196M [00:00<?, ?B/s]

train-00011-of-00016.parquet:   0%|          | 0.00/340M [00:00<?, ?B/s]

train-00012-of-00016.parquet:   0%|          | 0.00/401M [00:00<?, ?B/s]

train-00013-of-00016.parquet:   0%|          | 0.00/307M [00:00<?, ?B/s]

train-00014-of-00016.parquet:   0%|          | 0.00/305M [00:00<?, ?B/s]

train-00015-of-00016.parquet:   0%|          | 0.00/231M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/495k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/34782245 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2998 [00:00<?, ? examples/s]

In [4]:
def tokenize(sentence):
  return tokenizer(sentence, return_tensors="pt", padding=True).input_ids

In [5]:
class Hypothesis:
  def __init__(self, score=0, is_open=True, sequence=None, constraints=[]):
    self.score = score
    self.is_open = is_open
    self.sequence = sequence
    self.constraints = constraints


In [6]:
def init_grid(max_len, num_constraints):
  grid = []
  for i in range(max_len):
    row = []
    for j in range(num_constraints + 1):
        row.append([])
    grid.append(row)
  return grid

In [128]:
# generate new open hypotheses
def generate(model, hyp, input_ids, constraints):

  if hyp.sequence is not None:
    if hyp.sequence[-1, -1].item() == tokenizer.eos_token_id:
      return None

  # forward pass
  with torch.no_grad():
      encoder_outputs = model.get_encoder()(input_ids=input_ids)

  # initialize decoder input
  if hyp.sequence is None:
      decoder_input_ids = torch.tensor([[model.config.decoder_start_token_id]])
  else:
      decoder_input_ids = hyp.sequence

  with torch.no_grad():
    outputs = model(
        input_ids=None,
        encoder_outputs=encoder_outputs,
        decoder_input_ids=decoder_input_ids
    )
    logits = outputs.logits

  # get the logits for the last predicted token
  next_token_logits = logits[:, -1, :] # [batch_size, sequence_length, vocab_size]
  next_token_probs = torch.softmax(next_token_logits, dim=-1).squeeze(0)

  # get the token with the highest probability
  next_token_id = torch.argmax(next_token_probs).item()
  next_token_prob = next_token_probs[next_token_id].item()

  new_score = hyp.score + next_token_prob
  new_sequence = torch.cat([decoder_input_ids, torch.tensor([[next_token_id]])], dim=-1)

  next_token = tokenizer.decode([next_token_id], skip_special_tokens=True)

  # check if the decoded token is in the list of constraints
  if next_token in constraints:
    new_constraints = hyp.constraints + [next_token]
  else:
    new_constraints = hyp.constraints

  new_hyp = Hypothesis(new_score, True, new_sequence, new_constraints)

  return new_hyp


In [135]:
# start new constrained hypotheses
def start(model, hyp, input_ids, constraints):

  if hyp.sequence is not None:
    if hyp.sequence[-1, -1].item() == tokenizer.eos_token_id:
      return None

  for constraint in constraints:
    if constraint not in hyp.constraints:

      # get constraint tokens
      constraint_token_ids = tokenizer.encode(constraint, add_special_tokens=False)

      # forward pass
      with torch.no_grad():
          encoder_outputs = model.get_encoder()(input_ids=input_ids)

      # initialize decoder input
      if hyp.sequence is None:
          decoder_input_ids = torch.tensor([[model.config.decoder_start_token_id]])
      else:
          decoder_input_ids = hyp.sequence

      new_sequence = decoder_input_ids
      new_score = hyp.score

      for token_id in constraint_token_ids:
        with torch.no_grad():
          outputs = model(
              input_ids=None,
              encoder_outputs=encoder_outputs,
              decoder_input_ids=decoder_input_ids
          )
          logits = outputs.logits

        # get the logits for the last predicted token
        next_token_logits = logits[:, -1, :] # [batch_size, sequence_length, vocab_size]
        next_token_probs = torch.softmax(next_token_logits, dim=-1).squeeze(0)

        # get probability of constraint token
        constraint_token_prob = next_token_probs[token_id].item()

        new_score = new_score + constraint_token_prob
        new_sequence = torch.cat([new_sequence, torch.tensor([[token_id]])], dim=-1)

      new_constraints = hyp.constraints + [constraint]

      is_open = len(hyp.constraints) < len(constraints)

      new_hyp = Hypothesis(new_score, is_open, new_sequence, new_constraints)
      return new_hyp

  return None

In [110]:
# continue unfinished hypotheses
def cont(model, hyp, input_ids, constraints):
  return generate(model, hyp, input_ids, constraints)

In [139]:
tokenizer.decode(torch.tensor([[58100,  3814,   268,  3441,    16,  9382,  4944,     2,    11,   289,
          5012,    37,    11,   479,  9715,    38, 12303,   148, 24875,   104, 0
             ]]).flatten(), skip_special_tokens=False)

'<pad> München 1856: Vier Karten, die Ihre Sicht auf die Stadt verändern Ihren Blickr</s>'

In [136]:
def constrained_beam_search(model, input_ids, constraints, max_len, num_constraints, beam_size):

  """
  model: model
  input: example tokenized sentence
  constraints: constraints
  max_len: max_len of translation
  num_constraints: # of constraints
  beam_size: beam_size
  """
  start_hyp = Hypothesis() # initial hypothesis
  grid = init_grid(max_len, num_constraints) # initialize beams in grid
  grid[0][0] = [start_hyp]

  for t in range(1, max_len):
    for c in range(max(0, (num_constraints + t) - max_len), min(t, num_constraints) + 1):
      n, s, g = [], [], []

      for hyp in grid[t - 1][c]:
        if hyp.is_open:
          new_hyp = generate(model, hyp, input_ids, constraints)
          if new_hyp is not None:
            g.append(new_hyp)

      if c > 0:
        for hyp in grid[t - 1][c - 1]:
          if hyp.is_open:
            new_hyp = start(model, hyp, input_ids, constraints)
            if new_hyp is not None:
              s.append(new_hyp)
          else:
            new_hyp = cont(model, hyp, input_ids, constraints)
            if new_hyp is not None:
              n.append(new_hyp)

      all_hyps = sorted(n + s + g, key=lambda hyp: hyp.score, reverse=True)

      grid[t][c] = all_hyps[:beam_size] # k-best scoring hypotheses stay on the beam

  top_level_hyps = [] # get hyps in top level beams
  for t in range(len(grid)):
      top_level_hyps.append(grid[t][num_constraints])

  for hyps in top_level_hyps:
    for hyp in hyps:
      print(hyp.sequence, hyp.score)

  # finished_hyps =
  # best_hyp =
  #return best_hyp


In [137]:
input_ids = tokenize(de_en_dev[0]['translation']['en'])
constrained_beam_search(model, input_ids, ['Ihren Blick'], 30, 1, 2)

tensor([[58100,    38, 12303,   148, 24875]]) 4.671101629583063e-05
tensor([[58100,  3814,    38, 12303,   148, 24875]]) 0.9239952274481311
tensor([[58100,    38, 12303,   148, 24875,   104]]) 0.22157038335859625
tensor([[58100,  3814,   268,    38, 12303,   148, 24875]]) 1.84342563988816
tensor([[58100,  3814,    38, 12303,   148, 24875,   104]]) 1.1409874864737048
tensor([[58100,  3814,   268,  3441,    38, 12303,   148, 24875]]) 2.7991883233206636
tensor([[58100,  3814,   268,    38, 12303,   148, 24875,   104]]) 2.1128662908281015
tensor([[58100,  3814,   268,  3441,    16,    38, 12303,   148, 24875]]) 3.675833381027985
tensor([[58100,  3814,   268,  3441,    38, 12303,   148, 24875,   104]]) 3.115755565466202
tensor([[58100,  3814,   268,  3441,    16,  9382,    38, 12303,   148, 24875]]) 4.492873525392788
tensor([[58100,  3814,   268,  3441,    16,    38, 12303,   148, 24875,   104]]) 4.0143148668716435
tensor([[58100,  3814,   268,  3441,    16,  9382,  4944,    38, 12303,   14

In [101]:
# compute score using BLEU
def compute_score(prediction, actual):
  pass

In [9]:
de_en_dev[0]

{'translation': {'de': 'München 1856: Vier Karten, die Ihren Blick auf die Stadt verändern',
  'en': 'Munich 1856: Four maps that will change your view of the city'}}

In [10]:
tokenize(de_en_dev[0]['translation']['en'])

tensor([[ 4260,   268,  3441,    16,  9701, 12126,    35,    73,   866,    83,
           704,     7,     4,   642,     0]])